### ISSUE TITLE
left “ and right ” double quotation mark

### ISSUE THREAD

**Issue by carstengericke** [HCL-TECH-SOFTWARE/sametime-doc#1]
On sametime-doc/v1202/admin/t_configure_mongodb.html, there are a couple of left “ and right ” double quotation mark that prevent copy and paste.

**Comment by davidsayer57** [comment]
Thank you... should be fixed now.  https://opensource.hcltechsw.com/sametime-doc/v1202/admin/t_configure_mongodb.html
